
version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Expose port for frontend
    volumes:
      - .:/app  # Bind mount for live reloading
      - ./frontend:/usr/src/app  # Bind mount for frontend code
      - /usr/src/app/node_modules # Ensure node_modules are available inside the container
    environment:
      - VITE_HOST=0.0.0.0  # Allow frontend to be accessed externally
    command: npm run dev  # Run the frontend development server

  backend:
    depends_on:
      - frontend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env  # Supabase credentials are stored here
    command: npm run dev
