version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"        # Expose port for frontend
    volumes:
      - .:/app  # Bind mount for live reloading
      - ./frontend:/usr/src/app  # Bind mount for frontend code (this should work for hot-reloading)
      - /usr/src/app/node_modules # Ensure node_modules are available inside the container
    environment:
      - VITE_HOST=0.0.0.0       # Allow the frontend to be accessed externally
    command: npm run dev         # Run the development server

  backend:
    depends_on:
      - postgres
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    command: npm run dev

  postgres:
    image: postgres:latest
    container_name: campus_crave-db-1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=campus_crave_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "campus_crave_db"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:        # Declare the named volume for PostgreSQL data persistence
